import EffectKernel.PhaseD.T3_PositiveAuthorityOrigin
import EffectKernel.PhaseD.T5_ReservationPrecedesRelease
import EffectKernel.PhaseD.T6_UniqueAuthorizationLinearization
import EffectKernel.PhaseD.T7_AuthorizationSnapshotSufficiency

#print axioms EffectKernel.PhaseD.T3_positiveAuthorityOrigin
#print axioms EffectKernel.PhaseD.T5_reservationPrecedesRelease
#print axioms EffectKernel.PhaseD.T6_uniqueAuthorizationLinearization
#print axioms EffectKernel.PhaseD.T7_authorizationSnapshotSufficiency
