import EffectKernel.PhaseD.T3_PositiveAuthorityOrigin
import EffectKernel.PhaseD.T5_ReservationPrecedesRelease
import EffectKernel.PhaseD.T6_UniqueAuthorizationLinearization
import EffectKernel.PhaseD.T7_AuthorizationSnapshotSufficiency
import EffectKernel.PhaseD.T10_UncertainOutcomeConservatism
import EffectKernel.PhaseD.T11_ReplayExclusionNonResurrection
import EffectKernel.PhaseD.T12_TargetContractIdentityStability

#print axioms EffectKernel.PhaseD.T3_positiveAuthorityOrigin
#print axioms EffectKernel.PhaseD.T5_reservationPrecedesRelease
#print axioms EffectKernel.PhaseD.T6_uniqueAuthorizationLinearization
#print axioms EffectKernel.PhaseD.T7_authorizationSnapshotSufficiency
#print axioms EffectKernel.PhaseD.T10_uncertainOutcomeConservatism
#print axioms EffectKernel.PhaseD.T11_replayExclusionNonResurrection
#print axioms EffectKernel.PhaseD.T12_targetContractIdentityStability
#print axioms EffectKernel.PhaseD.T12_tcidChange_requiresDistinctAdmission
